# Init

## Colab

In [5]:

import os
import sys
import cv2
from glob import glob

is_colab = 'google.colab' in sys.modules

if is_colab:
    from google.colab import drive
    drive.mount('/content/drive')

    import os
    os.chdir('/content/drive/MyDrive/Smartech/MinaRumas')

    import sys
    sys.path.append('/content/drive/MyDrive/Smartech/MinaRumas')

    !ls
    !pip install -r requirements.txt
else:
    print("No está en Colab")

No está en Colab


## install

In [6]:
import ultralytics
ultralytics.checks()

Ultralytics 8.3.165  Python-3.10.11 torch-2.7.1+cpu CPU (11th Gen Intel Core(TM) i5-1135G7 2.40GHz)
Setup complete  (8 CPUs, 7.7 GB RAM, 66.5/89.5 GB disk)


## Prueba

In [7]:
import os
import cv2
import time
import json
import base64
import torch
import requests
import numpy as np
from datetime import datetime
from pathlib import Path
from collections import defaultdict, deque
from ultralytics import YOLO

# Librerías propias
from utils.paths import generar_output_video
from libs.config_loader import load_camera_config
from libs.main_functions import process_video

def main():
    start_time_sec = 0
    end_time_sec = 12
    camera_number = 1

    try:
        input_video, _, polygons, camera_sn, _, _ = load_camera_config(
            camera_number, config_path="mkdocs.yml"
        )
        output_video = generar_output_video(input_video)
        print(f"Procesando video: {input_video}")
        print(f"Salida: {output_video}")
    except ValueError as e:
        print(f"[Error] {e}")
        return

    model_det_path = 'models/model_detection.pt'
    model_seg_path = 'models/model_segmentation.pt'

    api_url = "https://fn-alma-mina.azurewebsites.net/api/alert"  # URL de la API

    process_video(
        video_path=input_video,
        output_path=output_video,
        start_time_sec=start_time_sec,
        end_time_sec=end_time_sec,
        model_det_path=model_det_path,
        model_seg_path=model_seg_path,
        detection_zone=polygons,
        camera_number=camera_number,
        camera_sn=camera_sn,
        api_url=api_url  # URL de la API
    )

    print("\n=== Procesamiento finalizado correctamente ===")

if __name__ == "__main__":
    main()


[INFO] Cargando configuración para cámara 1 desde 'mkdocs.yml'
[INFO] Matriz de homografía H:
 [[    0.51068      1.6783     -625.52]
 [   -0.58768      2.3023      153.15]
 [-0.00044831   0.0025899           1]]
Procesando video: video/video_cam3_0422.mp4
Salida: video\output\video_cam3_0422\output_video_cam3_0422_20250715_0201.mp4
Video: 1920x1080 @ 30.00 FPS
Procesando frames 0 a 360
Procesados 0 frames
Rumas activas: 0
Nueva ruma creada: ID 1
Nueva ruma creada: ID 2
💾 Save alert local ejecutándose
 Metadata de alerta: {'cameraSN': 'DS-7104NI-Q1-1', 'enterprise': 'alma', 'alert_type': 'movimiento_zona', 'timestamp': '2025-07-15 02:01:59', 'id': 2, 'percent': 99.97718197375927, 'centroid': (1172, 443), 'coords': None, 'radius': None, 'frame_number': 18, 'video_time_seconds': 0.5999641722779825}
📄 Imagen resumen de rumas guardada en: alerts_save\2025-07-15_local\02-01-59_ruma_summary_18.jpg
 Alerta local guardada: movimiento_zona - 02:01:59
💾 Save alert local ejecutándose
 Metadata de

KeyboardInterrupt: 

In [ ]:
"""
!grep "class " /content/drive/MyDrive/Smartech/MinaRumas/monitor/ruma_monitor.py
!python3 -m py_compile /content/drive/MyDrive/Smartech/MinaRumas/monitor/ruma_monitor.py
print("ok")
!python3 -m py_compile monitor/ruma_monitor.py
!python3 /content/drive/MyDrive/Smartech/MinaRumas/monitor/ruma_monitor.py
"""

'\n!grep "class " /content/drive/MyDrive/Smartech/MinaRumas/monitor/ruma_monitor.py\n!python3 -m py_compile /content/drive/MyDrive/Smartech/MinaRumas/monitor/ruma_monitor.py\nprint("ok")\n!python3 -m py_compile monitor/ruma_monitor.py\n!python3 /content/drive/MyDrive/Smartech/MinaRumas/monitor/ruma_monitor.py\n'